### PR TITLE
Blue note: pink image pattern

### PR DESCRIPTION
**Pull request by MaggieCabrera**
Adds this pattern:

Screenshot 2023-08-03 at 13 54 09

### CODE REVIEW

**Comment by kafleg** [comment]
The PR looks fine. But why the image is not skewed/tild? 
image

**Comment by MaggieCabrera** [comment]
what browser are you using? do you see the clip path for the other two image variations (the striped ones)?

**Comment by kafleg** [comment]
what browser are you using? 
- I'm using edge browser.

**Comment by kafleg** [comment]
This pattern is fine, 
image

**Comment by MaggieCabrera** [comment]
ok I think it's an edge thing, and I might have a way to fix it, I'll ping you to test again when I have it

**Comment by kafleg** [comment]
> ok I think it's an edge thing, and I might have a way to fix it, I'll ping you to test again when I have it

Sounds good.

**Comment by MaggieCabrera** [comment]
> Sounds good.

@kafleg this issue was happening in Chrome too and I think my fix should have applied to Edge too, please tell me if that is the case. The fix also affected the other two patterns Striped image and text and Striped image, text and button

**Comment by kafleg** [comment]
It is now fixed. Ready to merge @MaggieCabrera

**Comment by MaggieCabrera** [comment]
Can you give me the green check? you should have permissions for it

**Comment by kafleg** [comment]
> Can you give me the green check? you should have permissions for it

I'm not able to get you. I only have close PR permission.

**Review by kafleg — APPROVED** [review]
Looks good to me. Ready for merge.

**Pull request merged**
