### PR TITLE
Update readme with correct playground link

### LINKED ISSUE #30: Playground link does not install Create block theme plugin
When I visit this link in the readme,  only Gutenberg is installed.

https://developer.wordpress.org/playground/demo/?step=playground&theme=twentytwentythree&plugin=gutenberg&plugin=create-block-theme.1.3.8.zip&url=/wp-admin/index.php

### PR DESCRIPTION
**Pull request by MaggieCabrera**
Closes https://github.com/WordPress/community-themes/issues/30

What it says in the title :D

### CODE REVIEW

**Review by mikachan — APPROVED** [review]
Looks good to me!

**Comment by carolinan** [comment]
Is there no way to not have to include the version number? Since this will keep changing 😄

**Comment by MaggieCabrera** [comment]
> Is there no way to not have to include the version number? Since this will keep changing 😄

I asked @adamziel and he said that not for the moment, sadly!

**Comment by adamziel** [comment]
Actually, if you skip the version number then it will install the latest stable release:

https://playground.wordpress.net/?theme=twentytwentythree&plugin=gutenberg&plugin=create-block-theme

**Pull request merged**
