### PR TITLE
Blue Note: Vertically center the post title and date

### PR DESCRIPTION
**Pull request by scruffian**
According to the figma the post tile and date should be vertically aligned:

Screenshot 2023-07-26 at 09 36 06

### CODE REVIEW

**Comment by getdave** [comment]
What's the best way to review this? Which template is it?

**Comment by MaggieCabrera** [comment]
header large is used in single templates I believe

**Comment by carolinan** [comment]
This is already part of https://github.com/WordPress/community-themes/pull/67

**Comment by scruffian** [comment]
This isn't needed.

**Pull request closed without merging**
