### PR TITLE
Blue note: Home template

### PR DESCRIPTION
**Pull request by MaggieCabrera**
I had the zip file for the home page in my DMs! Thank you @Mooore for working on this

### CODE REVIEW

**Comment by scruffian** [comment]
I made a change to the footer as I think this is the design intent:
Screenshot 2023-07-24 at 10 30 07

**Comment by MaggieCabrera** [comment]
Looking at the design I think all of the content in the black area should extend the same width, and probably make it wide width, I'm not sure what it is from your screenshot.

**Comment by MaggieCabrera** [comment]
I made comments on https://github.com/WordPress/community-themes/issues/5 but yeah, aligning the footer with the content should be on that list

**Comment by scruffian** [comment]
Like this?
Screenshot 2023-07-24 at 14 03 19

**Comment by MaggieCabrera** [comment]
yeah, it makes sense to me that either everything align or none of it is

**Comment by carolinan** [comment]
The no results block only contains the placeholder, compared to https://github.com/WordPress/community-themes/pull/65/files#diff-be779912416c3055199e2a71598bfa1e684f93750edd3769fafd203ac2079989R35

**Review by scruffian — APPROVED** [review]
This is looking good. I think we should merge and iterate.

**Pull request merged**
