### PR TITLE
Update style and readme file

### PR DESCRIPTION
**Pull request by kafleg**

### CODE REVIEW

**Review by MaggieCabrera — APPROVED** [review]

**Comment by kafleg** [comment]
I need a description as well.

**Comment by kafleg** [comment]
@MaggieCabrera 
We are going to delete this PR?

**Comment by MaggieCabrera** [comment]
oh no, I thought i merged this when I reviewed it! let me add your changes

**Comment by MaggieCabrera** [comment]
ugh I can't because it's on your fork, can you rebase it? your changes are correct and relevant

**Comment by kafleg** [comment]
All the changes are already made in Trunk from your previous PR. Except fixing theme check issue. Can you merge that commit and we can close this PR.

**Comment by MaggieCabrera** [comment]
> All the changes are already made in Trunk from your previous PR. Except fixing theme check issue. Can you merge that commit and we can close this PR.

You merged my PR, we also need the change to the name of the contributors and theme URL and tags

**Comment by kafleg** [comment]
No idea what to do.

**Comment by MaggieCabrera** [comment]
Try to rebase this one or open a new PR if you prefer?

**Comment by kafleg** [comment]
I can create new PR, that seems easy to me.

**Comment by MaggieCabrera** [comment]
Thank you! and sorry for the misunderstanding

**Comment by kafleg** [comment]
> Thank you! and sorry for the misunderstanding

Not an issue. I'm also learning many things in GitHub.

**Pull request closed without merging**
