### PR TITLE
Term: Add Pattern Outlined Media & Text

### LINKED ISSUE #107: Term: Pattern Outlined Media & Text
Block Pattern_ Outlined Media   Text
https://www.figma.com/community/file/1263420783737936752

### PR DESCRIPTION
**Pull request by MaggieCabrera**
Brings the changes from https://github.com/WordPress/community-themes/pull/153

Closes https://github.com/WordPress/community-themes/issues/107

Screenshot 2024-06-04 at 19 25 57

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
Can someone test this one for me, please?

**Comment by giacomo-secchi** [comment]
The image looks collapsed on mobile
demo-store local_

**Comment by shail-mehta** [comment]
@MaggieCabrera 

Can we use `get_template_directory_uri()` instead of `get_stylesheet_directory_uri()` ? because Term is Main Theme.

**Comment by MaggieCabrera** [comment]
I added the changes here from https://github.com/WordPress/community-themes/pull/213 into this and changed the get_stylesheet_directory_uri to get_template_directory_uri

**Pull request merged**
