### PR TITLE
Blue note: launch tasks

### LINKED ISSUE #89: Blue note: Launch tasks
There are a few issues that still need to be looked into:

- https://github.com/WordPress/community-themes/issues/78 (I don't feel we need to add all the patterns, but there are still a few that I think merit being included before launch)
- https://github.com/WordPress/community-themes/issues/11 has a patch ready
- https://github.com/WordPress/community-themes/issues/8 it's minor but should be easy to fix

Besides that we need to:

- [x] Add credit to the people that worked on the theme lately (@getdave, @jeryj and @ajlende I believe)
- [x] Add credit for the images we added
- [x] The theme check plugin only shows one warning:
> WARNING: Found a translation function that is missing a text-domain in the file patterns/hidden-404.php. Function esc_html_e, with the arguments 'Search the site'. 
- [x] Check that the theme tags are accurate
- [x] Add credits for the fonts included in the theme
- [x] Update the version to 1.0.0 and add a changelog entry
- [x] Change contributors on the readme and styles.css file to `wordpressdotorg` and the author URL to be `https://wordpress.org/themes/author/wordpressdotorg/`
- [x] Add a theme description, @beafialho can you help with this?

### PR DESCRIPTION
**Pull request by MaggieCabrera**
Closes https://github.com/WordPress/community-themes/issues/89

- [x] Add credit to the people that worked on the theme lately 
- [x] Add credit for the images we added
- [x] Add credit for the fonts used
- [x] Add a theme description

### CODE REVIEW

**Comment by MaggieCabrera** [comment]
@kafleg have a look!

**Comment by kafleg** [comment]
= 0.0.1 =
* Initial release

This should be 1.0.0? 

Rest is looks good to me.

**Comment by kafleg** [comment]
You missed to add my name in the credits ;)

**Comment by MaggieCabrera** [comment]
> You missed to add my name in the credits ;)

no, you are there from before, check again!

**Review by kafleg — APPROVED** [review]
Looks good.

**Pull request merged**
