### PR TITLE
Blue note: bump version and updated changelog

### PR DESCRIPTION
**Pull request by MaggieCabrera**

### CODE REVIEW

**Review by kafleg — APPROVED** [review]

**Comment by kafleg** [comment]
@MaggieCabrera 

We have two headers in this theme.  One header is used in home and archive pages, another header is in single page.

I saved the navigation menu in the home page but the menu is not appearing on the single page. Do I need to save the menu again in a single page as well?

**Comment by kafleg** [comment]
image
Header home page and the menu.

**Comment by kafleg** [comment]
image

Inner page(single page) menu.

**Comment by MaggieCabrera** [comment]
> image
> 
> Inner page(single page) menu.

You are right, I fixed it on https://github.com/WordPress/community-themes/pull/99 can you check?

**Pull request merged**
